import { decide, netEdge, remainingMinutes } from "../core.js";
import { buildKeirinFormation, keirinTicketEdge } from "./core.js";

const VENUES=["函館","青森","いわき平","弥彦","前橋","取手","宇都宮","大宮","西武園","京王閣","立川","松戸","川崎","平塚","小田原","伊東温泉","静岡","名古屋","岐阜","大垣","豊橋","富山","松阪","四日市","福井","奈良","向日町","和歌山","岸和田","玉野","広島","防府","高松","小松島","高知","松山","小倉","久留米","武雄","佐世保","別府","熊本"];
const STORE="keirin-edge-lab-races-v1";const $=(s)=>document.querySelector(s);let state=load();let activeKey="";
const el={date:$("#raceDate"),venue:$("#venue"),race:$("#raceNumber"),rows:$("#riderRows"),decision:$("#decision"),main:$("#mainTickets"),cover:$("#coverTickets"),ranking:$("#rankingGrid"),skip:$("#skipList")};
function load(){try{return JSON.parse(localStorage.getItem(STORE))||{}}catch{return{}}}function persist(){localStorage.setItem(STORE,JSON.stringify(state))}function today(){return new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo"}).format(new Date())}function key(){return `${el.date.value}|${el.venue.value}|${el.race.value}`}function lines(v){return String(v||"").split(/\r?\n/).map(v=>v.trim()).filter(Boolean).slice(0,5)}
function cls(s){return s==="UP"?"up":s==="DOWN"?"down":s==="WATCH"?"watch":"blocked"}function setStatus(n,s){n.textContent=s;n.className=cls(s)}function pct(v,d=1){return v!==""&&Number.isFinite(Number(v))?`${Number(v).toFixed(d)}%`:"--"}
function addRider(r={}){if(el.rows.children.length>=9)return;const row=$("#riderTemplate").content.firstElementChild.cloneNode(true);row.querySelector('[data-field="number"]').value=r.number??"";row.querySelector('[data-field="name"]').value=r.name??"";row.querySelector('[data-field="style"]').value=r.style||"追";row.querySelector('[data-field="score"]').value=r.score??"";row.querySelector('[data-action="remove"]').onclick=()=>{row.remove();preview()};row.querySelectorAll("input,select").forEach(i=>i.addEventListener("input",preview));el.rows.append(row)}
function riders(){return [...el.rows.children].map(row=>({number:Number(row.querySelector('[data-field="number"]').value),name:row.querySelector('[data-field="name"]').value.trim(),style:row.querySelector('[data-field="style"]').value,score:Number(row.querySelector('[data-field="score"]').value)})).filter(r=>r.number||r.name||r.score)}
function fromForm(){return{date:el.date.value,venue:el.venue.value,race:Number(el.race.value),startTime:$("#startTime").value,observedAt:$("#observedAt").value,modelProbability:$("#modelProbability").value,marketProbability:$("#marketProbability").value,confidence:$("#confidence").value,agreement:$("#agreement").value,dataRate:$("#dataRate").value,costRate:$("#costRate").value,linePlan:$("#linePlan").value.trim(),reasons:lines($("#reasons").value),invalidConditions:$("#invalidConditions").value.trim(),riders:riders(),ticketOdds:state[activeKey]?.ticketOdds||{},savedAt:new Date().toISOString()}}
function fill(r={}){$("#startTime").value=r.startTime||"";$("#observedAt").value=r.observedAt||"";for(const id of ["modelProbability","marketProbability","confidence","agreement","dataRate"])$("#"+id).value=r[id]??"";$("#costRate").value=r.costRate??"2";$("#linePlan").value=r.linePlan||"";$("#reasons").value=(r.reasons||[]).join("\n");$("#invalidConditions").value=r.invalidConditions||"";el.rows.replaceChildren();(r.riders?.length?r.riders:Array.from({length:7},()=>({}))).forEach(addRider)}
function ticketRows(target,tickets,record){if(!tickets.length){target.innerHTML='<div class="empty">評価済み選手を5人以上入力してください</div>';return}const ranked=tickets.map(ticket=>{const odds=record.ticketOdds?.[ticket.join("-")]||"";return{ticket,odds,edge:keirinTicketEdge(record.riders||[],ticket,odds,record.costRate)}}).sort((a,b)=>(b.edge??-Infinity)-(a.edge??-Infinity));target.replaceChildren(...ranked.map(({ticket,odds,edge})=>{const row=document.createElement("div");row.className="ticket";row.innerHTML=`<div class="picks">${ticket.map(n=>`<b>${n}</b>`).join("")}</div><input type="number" min="1.1" step=".1" aria-label="${ticket.join("-")}の3連単オッズ" placeholder="オッズ" value="${odds}"><em>${edge===null?"edge --":`edge ${edge>=0?"+":""}${edge.toFixed(1)}%`}</em>`;row.querySelector("input").onchange=e=>{const current=state[activeKey]||fromForm();current.ticketOdds||={};current.ticketOdds[ticket.join("-")]=e.target.value;state[activeKey]=current;persist();render(current)};return row}))}
function renderTickets(r){const f=buildKeirinFormation(r.riders||[]);ticketRows(el.main,f.main,r);ticketRows(el.cover,f.cover,r)}function preview(){renderTickets(fromForm())}
function render(r={}){const result=decide(r);setStatus(el.decision,result.status);$("#modelValue").textContent=pct(r.modelProbability);$("#marketValue").textContent=pct(r.marketProbability);const edge=netEdge(r.modelProbability,r.marketProbability,r.costRate);$("#edgeValue").textContent=edge===null?"--":`${edge>=0?"+":""}${edge.toFixed(1)}%`;$("#confidenceValue").textContent=pct(r.confidence,0);$("#agreementValue").textContent=pct(r.agreement,0);const rem=remainingMinutes(r.date,r.startTime);$("#remainingValue").textContent=rem===null?"--":rem<0?"発走済":`${Math.floor(rem)}分`;renderTickets(r);dashboard()}
function openRace(){activeKey=key();const r=state[activeKey]||{date:el.date.value,venue:el.venue.value,race:Number(el.race.value),ticketOdds:{}};fill(r);render(r);history.replaceState(null,"",`?date=${encodeURIComponent(el.date.value)}&venue=${encodeURIComponent(el.venue.value)}&race=${el.race.value}#review`)}
function dashboard(){const records=Object.values(state).filter(r=>r.date===el.date.value);const assessed=records.map(record=>({record,result:decide(record),edge:netEdge(record.modelProbability,record.marketProbability,record.costRate)}));const eligible=assessed.filter(x=>["UP","DOWN"].includes(x.result.status)).sort((a,b)=>(b.edge??-999)-(a.edge??-999));el.ranking.replaceChildren(...(eligible.length?eligible.map((x,i)=>{const a=document.createElement("article");a.className="rank-card";a.innerHTML=`<div class="rank-top"><span>#${i+1}</span><b class="${cls(x.result.status)}">${x.result.status} · ${x.result.reason}</b></div><h3>${x.record.venue} ${x.record.race}R</h3><p>${x.record.linePlan||x.record.reasons?.[0]||"ライン未入力"}</p><div class="rank-score"><strong>${x.edge?.toFixed(1)}%</strong><span>confidence ${x.record.confidence}%</span></div>`;return a}):[Object.assign(document.createElement("div"),{className:"empty",textContent:"安全基準を通過したレースはありません。見送りを維持します。"})]));const skips=assessed.filter(x=>["WATCH","DATA BLOCKED"].includes(x.result.status));el.skip.innerHTML=skips.length?`<div class="skip-list">${skips.map(x=>`<div class="skip-item"><span>${x.record.venue} ${x.record.race}R</span><b>${x.result.status} · ${x.result.reason}</b></div>`).join("")}</div>`:'<div class="empty">登録済みの見送り対象はありません</div>';const complete=assessed.filter(x=>Number(x.record.dataRate)>=95).length;$("#coverage").textContent=records.length?`${Math.round(complete/records.length*100)}%`:"0%";$("#raceCount").textContent=records.length;const strict=eligible.filter(x=>Number(x.record.confidence)>=70).length,experimental=eligible.filter(x=>Number(x.record.confidence)>=60&&Number(x.record.confidence)<70).length;$("#strictCount").textContent=strict;$("#experimentalCount").textContent=experimental;const global=eligible.length?"UP":records.length?"WATCH":"DATA BLOCKED";setStatus($("#globalStatus"),global);setStatus($("#rankingStatus"),global)}
VENUES.forEach(v=>el.venue.add(new Option(v,v)));for(let i=1;i<=12;i++)el.race.add(new Option(`${i}R`,String(i)));const q=new URLSearchParams(location.search);el.date.value=q.get("date")||today();el.venue.value=q.get("venue")||"平塚";el.race.value=q.get("race")||"1";$("#raceSelector").onsubmit=e=>{e.preventDefault();openRace()};$("#manualForm").onsubmit=e=>{e.preventDefault();const r=fromForm();state[activeKey]=r;persist();render(r)};$("#addRider").onclick=()=>addRider();$("#clearRace").onclick=()=>{if(confirm("このレースの端末内入力を消去しますか？")){delete state[activeKey];persist();openRace()}};$("#shareButton").onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$("#shareButton").textContent="コピー済み"}catch{prompt("共有URL",location.href)}setTimeout(()=>$("#shareButton").textContent="共有URL",1500)};openRace();setInterval(()=>render(state[activeKey]||fromForm()),60000);
